### ISSUE TITLE
Search results not showing properties

### ISSUE THREAD

**Issue by headgood17** [Markup360/realestatepro#16]
When I search property in the property form, the result jumps to the page that show "It looks like nothing was found at this location. Maybe try one of the links below or conduct a search?" How can I make the property search result page?

**Comment by headgood17** [comment]
This is the property search result page.
![image](https://cloud.githubusercontent.com/assets/26901526/24825042/3e61e928-1c49-11e7-9fad-ca5b3ec63c44.png)

**Comment by Markup360** [comment]
Under Admin>Pages do you have this page?

>Property Search Results

**Comment by headgood17** [comment]
I have this page. But when I search properties, the page showed the words, "It looks like nothing was found at this location. Maybe try one of the links below or conduct a search?". How can I change it into being searchable?

**Comment by Markup360** [comment]
If you delete the page completely RealEstatePro will automatically re-create it. If you deleted the page but it is still in Pages>Trash (it's a link) then because the page still exists it will not be re-created but at the same time because it is deleted RealEstatePro can't use it If you created a new page and the old page is still in the trash the new page will have a different slug/permalink. So you need to find it in the trash and restore it, or permanently delete it and let RealEstatePro recreate it.﻿
