### ISSUE TITLE
Realestatepro Listing Pages

### ISSUE THREAD

**Issue by Johnkm09** [Markup360/realestatepro#18]
Hi,how can I edit the real estate single property listing page?The image appears to be so big and when I edit css to make it smaller,it expands and shrinks  on click which makes it unstable,any help please!!Thanks

**Comment by Markup360** [comment]
The image is 891px wide if you are using a sidebar which is pretty average, if however, you want to change it the best way to do it is from the `jquery.lightslider.js` file in the `js` folder. However, you should make your changes in a child theme otherwise they will be overwritten if you update the theme,

**Comment by Markup360** [comment]
Another way, probably a easier is to use this CSS in a custom CSS file in your child theme or the actual style.css in the child theme.

```
#image-gallery img {
	width: 600px;
	height: 480px;
}
```

**Comment by Johnkm09** [comment]
Thanks,that works,is it possible to add reviews and feedbacks to the single listings page and how can I fix the issue with google map not displaying?Thanks for the assistance.

**Comment by Markup360** [comment]
For Google Maps see this page
http://www.markup360.com/content/10-using-google-maps-api-key

If that doesn't help and for more help on reviews please open another thread.
