### ISSUE TITLE
Property Search only indexing single words

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#7]
I've launched our site and confirmed the following issue using various different devices, networks and browsers...

The Property Search widget appears to only return results for single words. Any combination of multiple words returns: "No properties matched your search criteria"

Three Examples:

1. We have properties in "Lake City, Colorado".
A search for "lake" returns all 10 properties.
A search for "Lake City" returns no results.

2. We have properties in the "Horse River Ranch" subdivision.
A search for "horse" returns all 10 properties in Horse River Ranch.
A search for "Horse River Ranch" returns no results.

3. We have properties in "Crested Butte, Colorado".
A search for "crested" returns all properties in Crested Butte.
A search for "Crested Butte" returns no results.

Please feel free to test for yourself at paulvickersrealty.com

I'm guessing this is a bug, since I see no admin options regarding search indexing.

Any feedback is greatly appreciated.

Thanks! 

-Originally asked by agreda on 20-07-2016, 09:38 PM, migrated from site forum

**Comment by Markup360** [comment]
Thanks for bringing this to my attention, currently working on RealEstatePro so I will aim to fix and release this week.

**Comment by livingwandsworth** [comment]
Thanks for the update Naz! Happy to help test the release...

**Comment by Markup360** [comment]
This has now been fixed in the latest version. To update to the latest version;

1. Backup your site, and I recommend testing first before using on a live environment.
2. Download the latest version of RealEstatePro, open the package and copy the RealEstatePro theme folder.
3. From your installation go to wp-content/themes and delete your RealEstatePro theme.
4. Paste/transfer the latest version.

That should be all you need to do, if you run in to any issues let me know.

**Comment by livingwandsworth** [comment]
Just confirming that this update resolved the issue of multi-word searches.

Thanks again!
